
const result = {
    
    _id : '6a7e5bee2db69d02875296c3',
    fullname : "CHRISTIAN OKOTOAZA",
    studentId : "ZXY1016AVF",
    studentClass : "JSS 3",
    section: "2025 - 2026",
    term: "FIRST TERM",
    schoolName :"Khrystal tech",

    subjects: [
        {
            subjectName : "Mathematics",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "English Language",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Baisic Science",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Civic Education",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Home Economics",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Agricultural Science",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "PHE",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Cultural & Creative Arts",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "Computer Studies",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
        {
            subjectName : "French",
            firstTest : 9,
            secondTest : 10,
            cca: 10,
            exam: 50,
            total: 79,
            grade: "A",
            remark: "Very Good",
        },
    ],
        average: 89.5,
        score_obtainable: 200,
        score_obtain: 179,
        No_subj: "11",
        present: 108,
        absent: 6,
        Treport :"Excellent Performance. Keep It Up",
        tReport: "Excellent Performance. Keep It Up",
        createdAt:'2026-08-14T00:06:06.684+00:00',
        updatedAt:'2026-08-14T00:06:06.684+00:00',
}
const student = {
    fullname : "Khrystal Technology",
    studentId : "ZXY1016AVF",
    addmissionNo : "005",
    dob : "2009-01-01",
    class : "JSS 3",
    gender : "Male",
    house : "Golden",
    passport : "https://res.cloudinary.com/quizup/image/upload/v1786652759/school-logos/vmtxuarnixbregsssjiq.png",
    schoolName :"Khrystal tech",
}
module.exports = { result, student };